version: '3'
services:
  server:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
  db:
    image: mysql
    volumes:
      - ./db/schema:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db_volume: